<?php

function words_init(){
  //dpm('czkawka elisy');  
}

function words_menu(){
  $items = array();

  $items['words/list'] = array(
    'page callback' => 'words_list_words',
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM
  );
  
   $items['words/permcheck'] = array(
    'page callback' => 'words_permission_check',
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM
  );
 
  return $items;
}

function words_list_words(){
  $variables = array('myvar' => 'kiszeczki');
  $modulepath = drupal_get_path('module', 'words');
  return theme_render_template($modulepath.'/page--list--words.tpl.php', $variables);
}

function words_permission_check(){
  $variables = array('myvar' => 'trelemorele');
  $modulepath = drupal_get_path('module', 'words');
  return theme_render_template($modulepath.'/page--permission--check.tpl.php', $variables);
}


/**
 * Implements hook_block_info().
 */
function words_block_info() {
  $blocks = array();
  $blocks['my_block'] = array(
    'info' => t('My Custom Block'),
  );
  
  $blocks['my_test_block'] = array(
    'info' => t('My Test Block'),
  );   
  
  return $blocks;
}


function words_block_view($delta = '') {
  $block = array();
  switch($delta){
    case 'my_block':  
      if(user_access('access content')){ //good idea to check user perms here
         $block['subject'] = t('MYblock_TITLE');
         $block['content'] = words_list_words();
      }
      break;
    case 'my_test_block':  
      if(user_access('access content')){ //good idea to check user perms here
         $block['subject'] = t('My block data');
         $block['content'] = words_permission_check();
      }
      break;
  }
  return $block;
}
